version: '3'
services:
  sylladex:
    build: ./sylladex
    ports:
      - "${MAIN_PORT:-9000}:8080"
    volumes:
      - "./sylladex:/sylladex" # map host folder to container: changes are reflected immediately
      - "/sylladex/node_modules" # shadow node_modules so container doesn't pollute host with packages
      - "./persistence:/persistence"
    environment:
      - NODE_ENV
    restart: unless-stopped
